name: Check code style

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check code style
    steps:
      - uses: RojerGS/python-black-check@master
        with:
          line-length: "88"
          path: "."
