name: Generate wiki

on:
  push:
    branches:
      - master

jobs:
  build-n-publish:
    name: Build and publish Wiki
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: >-
          pip install pydoc-markdown mkdocs
      - name: Generate docs
        run: |
          mkdir docs
          pydoc-markdown -I codeforces_api/ --render-toc > docs/Home.md
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: docs/
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
